[package]
name = "chip-8-rust"
version = "0.1.0"
authors = ["asnimansari <asnim96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
